version: '3'
services:
  changergroupe:
    container_name: docker-changer-groupe
    restart: always
    build: ./Changergroupe
    ports:
      - '80:3000'
    links:
      - mongo
  mongo:
    container_name: docker-mongo
    image: mongo
    ports: 
      - '27017:27017'      